# Limpieza de datos

Vamos a aplicar el [checklist del Banco Mundial](https://dimewiki.worldbank.org/wiki/Checklist:_Data_Cleaning) en Python usando el [SciPy stack](https://www.scipy.org/stackspec.html), principalmente pandas

## 0. Prerequisitos

Aclaración: La próxima celda es para compatilibidad con Colab, NO ES RECOMENDADO realizar pip install desde un notebook.

In [1]:
import sys
in_colab = 'google.colab' in sys.modules

if in_colab:
  BASE_DIR = "https://github.com/DiploDatos/AnalisisYCuracion/raw/master/"
else:
  BASE_DIR = ".."
if 'ftfy' not in sys.modules:
    !pip install 'ftfy<5.6'

The system cannot find the file specified.

# 1. Importando los datos

# 1.1. Verificar que no hay problemas en la importación

In [2]:
import pandas as pd
pd.options.display.float_format = '{:.2f}'.format

# 1.2. Asegurar de tener ids/claves únicas

Pandas soporta índices en los DataFrames vamos a recargar el conjunto de datos

In [3]:
kickstarter_2018 = pd.read_csv(BASE_DIR + "/input/kickstarter-projects/ks-projects-201801.csv", 
                               parse_dates=["deadline","launched"],
                               index_col=['ID'])

#### Ejercicio 1:

Armar una tabla con todos los proyectos con nombres duplicados, ordenados para revisar agrupados.

In [4]:
duplicated = kickstarter_2018[kickstarter_2018.name.duplicated(keep=False)].sort_values(['name'])
duplicated

,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
ID,,,,,,,,,,,,,,
816998285,"""...The Last shall be first..."" LODB Lifestyle...",Fashion,Fashion,USD,2014-02-09,6500.00,2013-12-19 21:51:50,0.00,canceled,0,US,0.00,0.00,6500.00
815783250,"""...The Last shall be first..."" LODB Lifestyle...",Fashion,Fashion,USD,2014-03-01,6500.00,2014-01-03 20:39:16,37.00,failed,3,US,37.00,37.00,6500.00
1010584633,"""A Fresh Start""",Shorts,Film & Video,USD,2011-09-25,3000.00,2011-08-28 21:27:52,3000.00,successful,24,US,3000.00,3000.00,3000.00
713417995,"""A Fresh Start""",Documentary,Film & Video,USD,2013-03-27,5000.00,2013-01-26 03:51:47,1417.00,failed,26,US,1417.00,1417.00,5000.00
1880084695,"""American Sports Stories"" - An Athletic Quest",Shorts,Film & Video,USD,2015-08-26,100000.00,2015-06-27 02:02:00,100.00,failed,1,US,100.00,100.00,100000.00
422509694,"""American Sports Stories"" - An Athletic Quest",Television,Film & Video,USD,2017-05-14,100000.00,2017-04-14 00:08:52,1.00,failed,1,US,25.00,1.00,100000.00
866225086,"""City of Mercy"" (Canceled)",Film & Video,Film & Video,USD,2015-02-26,20000.00,2015-01-27 19:30:43,7248.00,canceled,9,US,7248.00,7248.00,20000.00
1760892298,"""City of Mercy"" (Canceled)",Television,Film & Video,USD,2014-08-28,15000.00,2014-07-29 13:12:21,11260.00,canceled,7,US,11260.00,11260.00,15000.00
1999958521,"""Color"" Music Video",Film & Video,Film & Video,USD,2016-06-06,5000.00,2016-05-07 01:56:36,0.00,canceled,0,"N,0""",nan,0.00,5000.00
870322805,"""Color"" Music Video",Music,Music,USD,2015-09-16,1100.00,2015-09-02 00:03:02,1100.00,undefined,0,"N,0""",nan,1100.00,1100.00
1413519345,"""Cut From the Illest Cloth"" - The Brand New Fu...",Hip-Hop,Music,USD,2014-03-26,9000.00,2014-03-01 19:32:15,1010.00,canceled,25,US,1010.00,1010.00,9000.00
1637334549,"""Cut From the Illest Cloth"" - The Brand New Fu...",Hip-Hop,Music,GBP,2014-03-04,14000.00,2014-02-02 16:00:57,225.00,canceled,7,GB,369.89,377.33,23478.12
1656736114,"""ONE""",Apps,Technology,USD,2016-02-25,10000.00,2016-01-26 17:37:04,0.00,failed,0,US,0.00,0.00,10000.00
159049492,"""ONE""",Classical Music,Music,USD,2016-09-26,10000.00,2016-08-12 03:19:12,10261.00,successful,113,US,1870.00,10261.00,10000.00
72198224,"""On The Road""",Tabletop Games,Games,USD,2014-01-01,20000.00,2013-12-02 22:19:48,612.00,failed,10,US,612.00,612.00,20000.00
996180421,"""On The Road""",Webseries,Film & Video,USD,2015-01-22,80000.00,2014-12-23 17:31:06,0.00,failed,0,US,0.00,0.00,80000.00
306461885,"""Pulse""- a new album from ""Blind Focus"" to sup...",Music,Music,CAD,2016-12-08,4000.00,2016-11-08 03:01:36,270.00,canceled,3,CA,44.77,204.90,3035.59
1023301684,"""Pulse""- a new album from ""Blind Focus"" to sup...",Music,Music,CAD,2016-12-17,4000.00,2016-11-17 09:45:59,0.00,canceled,0,CA,0.00,0.00,2959.89
516801004,"""Reflections""",Shorts,Film & Video,USD,2012-10-16,3000.00,2012-09-16 07:47:47,0.00,failed,0,US,0.00,0.00,3000.00
2007967203,"""Reflections""",Narrative Film,Film & Video,USD,2013-01-16,60000.00,2012-12-05 16:31:40,0.00,failed,0,US,0.00,0.00,60000.00
1223071711,"""RunRainbow"" Feature Film Sizzle Reel",Horror,Film & Video,USD,2016-11-11,3734.00,2016-10-27 21:59:08,715.00,failed,20,US,225.00,715.00,3734.00
2136175444,"""RunRainbow"" Feature Film Sizzle Reel",Thrillers,Film & Video,USD,2016-11-01,3734.00,2016-10-17 18:12:57,250.00,canceled,8,US,220.00,250.00,3734.00
1165257902,"""The Book of Sam"" Book One Graphic Novel",Comics,Comics,USD,2017-02-09,300.00,2017-01-10 17:09:27,111.00,failed,10,US,25.00,111.00,300.00
1606189204,"""The Book of Sam"" Book One Graphic Novel",Comics,Comics,USD,2017-02-05,5000.00,2017-01-06 01:55:34,5.00,canceled,1,US,0.00,5.00,5000.00
1823321664,"""What's in your spine?""",Young Adult,Publishing,USD,2017-04-18,800.00,2017-03-06 13:10:55,800.00,canceled,1,US,0.00,800.00,800.00
465144515,"""What's in your spine?""",Young Adult,Publishing,USD,2017-04-15,4946.00,2017-03-06 02:55:48,0.00,canceled,0,US,0.00,0.00,4946.00
234863316,#Elixir,Hip-Hop,Music,USD,2016-09-24,5000.00,2016-08-25 05:27:22,0.00,canceled,0,US,0.00,0.00,5000.00
2043567899,#Elixir,Hip-Hop,Music,USD,2016-09-30,5000.00,2016-08-25 23:04:09,0.00,failed,0,US,0.00,0.00,5000.00
1889457470,$50 for a 1k word short story on a topic of yo...,Anthologies,Publishing,CAD,2017-10-01,1000000.00,2017-08-02 17:37:10,0.00,canceled,0,CA,0.00,0.00,795228.63
1165878498,$50 for a 1k word short story on a topic of yo...,Anthologies,Publishing,CAD,2017-10-01,50.00,2017-08-02 18:01:49,50.00,successful,1,CA,0.00,39.76,39.76
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255984219,noparkticket.com,Apps,Technology,USD,2015-11-22,20000.00,2015-09-23 01:56:42,5.00,failed,1,US,5.00,5.00,20000.00
1945927325,noparkticket.com,Web,Technology,USD,2015-05-29,156000.00,2015-04-23 18:45:30,0.00,failed,0,US,0.00,0.00,156000.00
145035452,project (Canceled),Food,Food,USD,2011-08-19,5000.00,2011-07-20 21:07:17,0.00,canceled,0,US,0.00,0.00,5000.00
1297288919,project (Canceled),Mixed Media,Art,USD,2016-02-14,47000.00,2016-01-06 16:11:52,0.00,canceled,0,US,0.00,0.00,47000.00
1146277333,returning at a later date (Canceled),Fiction,Publishing,USD,2015-05-25,250.00,2015-04-30 22:01:59,1238.00,canceled,16,US,1238.00,1238.00,250.00
1556035715,returning at a later date (Canceled),Experimental,Theater,USD,2015-10-10,99.00,2015-09-25 20:38:59,100.00,canceled,2,US,100.00,100.00,99.00
391083153,returning at a later date (Canceled),Periodicals,Publishing,USD,2015-10-05,1.00,2015-09-25 01:42:42,50.00,canceled,2,US,50.00,50.00,1.00
1586289411,returning at a later date (Canceled),Food,Food,USD,2015-11-24,99.00,2015-11-14 06:14:14,30.00,canceled,2,US,30.00,30.00,99.00
576148925,sFTP Client,Apps,Technology,GBP,2016-12-04,10000.00,2016-11-04 16:21:01,103.50,canceled,10,GB,109.09,130.20,12580.04
467374509,sFTP Client,Apps,Technology,GBP,2016-12-31,80000.00,2016-11-03 15:27:16,0.00,canceled,0,GB,0.00,0.00,98907.08
1331807604,smartLED,Hardware,Technology,EUR,2018-01-06,10000.00,2017-12-07 09:34:41,56.00,live,5,FR,100.63,67.97,12136.95
216839969,smartLED,Hardware,Technology,EUR,2017-12-28,10000.00,2017-11-28 09:22:51,66.00,canceled,6,FR,78.70,79.15,11993.00
167364797,test (Canceled),Digital Art,Art,GBP,2016-03-20,360.00,2016-02-20 00:10:45,100.00,canceled,1,GB,143.03,141.30,508.68
1404511608,test (Canceled),Space Exploration,Technology,USD,2015-04-18,49000.00,2015-03-19 02:40:10,1333.00,canceled,10,US,1333.00,1333.00,49000.00
1117671370,test (Canceled),Web,Technology,USD,2014-09-06,20000.00,2014-07-08 02:12:30,5.00,canceled,1,US,5.00,5.00,20000.00
1492548024,weSTAND: A Stand With a Mission,Gadgets,Technology,USD,2016-01-25,200.00,2016-01-04 17:33:28,1728.60,successful,58,US,1728.60,1728.60,200.00
1863478885,weSTAND: A Stand With a Mission,Gadgets,Technology,USD,2015-10-18,7000.00,2015-09-18 21:39:35,530.00,failed,19,US,530.00,530.00,7000.00
1334808206,x,Film & Video,Film & Video,GBP,2016-04-01,2000.00,2016-02-21 19:53:48,0.00,undefined,0,"N,0""",nan,0.00,2861.93
774948469,x,Apps,Technology,USD,2014-12-19,1500.00,2014-11-18 04:56:32,151.00,failed,4,US,151.00,151.00,1500.00
1955983697,x (Canceled),Software,Technology,USD,2011-02-21,20000.00,2011-01-21 00:21:20,0.00,canceled,0,US,0.00,0.00,20000.00
983316237,x (Canceled),Fiction,Publishing,USD,2012-07-24,10000.00,2012-06-26 22:15:19,0.00,canceled,0,US,0.00,0.00,10000.00
58345768,x (Canceled),Children's Books,Publishing,USD,2016-07-24,15000.00,2016-05-25 06:48:32,0.00,canceled,0,US,0.00,0.00,15000.00
1612055887,x (Canceled),Fiction,Publishing,USD,2012-02-22,15000.00,2012-01-12 01:07:01,0.00,canceled,0,US,0.00,0.00,15000.00
234114061,x (Canceled),Fashion,Fashion,USD,2013-09-03,5900.00,2013-07-29 20:14:48,0.00,canceled,0,US,0.00,0.00,5900.00
1839948714,xxx (Canceled),Food,Food,USD,2014-04-26,55000.00,2014-03-21 18:45:06,13591.00,canceled,156,US,13591.00,13591.00,55000.00
329580179,xxx (Canceled),Art,Art,USD,2011-09-03,10000.00,2011-06-05 04:54:37,1151.00,canceled,18,US,1151.00,1151.00,10000.00
1848699072,NaN,Narrative Film,Film & Video,USD,2012-02-29,200000.00,2012-01-01 12:35:31,100.00,failed,1,US,100.00,100.00,200000.00
634871725,NaN,Video Games,Games,GBP,2013-01-06,2000.00,2012-12-19 23:57:48,196.00,failed,12,GB,317.73,316.05,3224.97
648853978,NaN,Product Design,Design,USD,2016-07-18,2500.00,2016-06-18 05:01:47,0.00,suspended,0,US,0.00,0.00,2500.00
796533179,NaN,Painting,Art,USD,2011-12-05,35000.00,2011-11-06 23:55:55,220.00,failed,5,US,220.00,220.00,35000.00

# 1.3. Despersonalizar datos y guardarlos en un nuevo archivo

#### Ejercicio 2:

Verificar que los proyectos que tienen nombres duplicados también tienen el hash de nombre duplicado

In [5]:
from hashlib import md5
kickstarter_2018['name']=str(kickstarter_2018['name'])
def hashit(val):
    return md5(val.encode('utf-8'))

kickstarter_2018['name'].apply(hashit)
duplicated = kickstarter_2018[kickstarter_2018.name.duplicated(keep=False)].sort_values(['name'])

In [6]:
original_count = duplicated.shape[0]
duplicated['name_hash']=duplicated['name'].apply(hashit)
duplicated_count=duplicated[['name', 'name_hash']].duplicated().shape[0]
original_count, duplicated_count

(378661, 378661)

# 1.4. Nunca modificar los datos crudos u originales

In [7]:
import os
if not os.path.exists(BASE_DIR + "/output/"):
    os.makedirs(BASE_DIR + "/output/")

In [8]:
if not in_colab:
  kickstarter_2018.to_csv(BASE_DIR + "/output/ks-projects-201801-for-pandas.csv")


# 2. Pasos necesarios

In [9]:
#import pandas as pd
if not in_colab:
  kickstarter_2018 = pd.read_csv(BASE_DIR + "/output/ks-projects-201801-for-pandas.csv",
                        index_col='ID',
                        parse_dates=['deadline','launched'])

In [10]:
kickstarter_2018.describe(include='all')

,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
count,378661,378661,378661,378661,378661,378661.00,378661,378661.00,378661,378661.00,378661,374864.00,378661.00,378661.00
unique,1,159,15,14,3164,nan,378089,nan,6,nan,23,nan,nan,nan
top,ID\n1000002330 The Songs ...,Product Design,Film & Video,USD,2014-08-08 00:00:00,nan,1970-01-01 01:00:00,nan,failed,nan,US,nan,nan,nan
freq,378661,22314,63585,295365,705,nan,7,nan,197719,nan,292627,nan,nan,nan
first,NaN,NaN,NaN,NaN,2009-05-03 00:00:00,nan,1970-01-01 01:00:00,nan,NaN,nan,NaN,nan,nan,nan
last,NaN,NaN,NaN,NaN,2018-03-03 00:00:00,nan,2018-01-02 15:02:31,nan,NaN,nan,NaN,nan,nan,nan
mean,NaN,NaN,NaN,NaN,NaN,49080.79,NaN,9682.98,NaN,105.62,NaN,7036.73,9058.92,45454.40
std,NaN,NaN,NaN,NaN,NaN,1183391.26,NaN,95636.01,NaN,907.19,NaN,78639.75,90973.34,1152950.06
min,NaN,NaN,NaN,NaN,NaN,0.01,NaN,0.00,NaN,0.00,NaN,0.00,0.00,0.01
25%,NaN,NaN,NaN,NaN,NaN,2000.00,NaN,30.00,NaN,2.00,NaN,16.98,31.00,2000.00
50%,NaN,NaN,NaN,NaN,NaN,5200.00,NaN,620.00,NaN,12.00,NaN,394.72,624.33,5500.00
75%,NaN,NaN,NaN,NaN,NaN,16000.00,NaN,4076.00,NaN,56.00,NaN,3034.09,4050.00,15500.00
max,NaN,NaN,NaN,NaN,NaN,100000000.00,NaN,20338986.27,NaN,219382.00,NaN,20338986.27,20338986.27,166361390.71

## 2.1. Etiquetas de variables/columnas: no usar caracteres especiales

In [11]:
# helpful character encoding module
import chardet

¿Por qué? Por que aun hay limitaciones para trabajar con estos caracteres.

¿Cúales son los caracteres "normales"?

In [12]:
import string

string.ascii_letters + string.digits

'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'

#### Ejercicio 3

Comparar la cantidad de nombres raros en kickstarter_2018 con la que obtenemos al cargar 'ks-projects-201801.csv' con encoding iso-8859-1.

In [13]:
import ftfy.badness as bad

def weird(val):
    if isinstance(val, float): 
        return 0
    return bad.sequence_weirdness(val)

kickstarter_2018w = pd.read_csv(BASE_DIR + "/input/kickstarter-projects/ks-projects-201801.csv", encoding='iso-8859-1')
kickstarter_2018w['name_weirdness'] = kickstarter_2018w['name'].apply(weird)
kickstarter_2018w[kickstarter_2018w['name_weirdness'] > 1]['name_weirdness'].count()

ModuleNotFoundError: No module named 'ftfy'

## 2.3. Codificar variables

Para trabajar con los algoritmos de aprendizaje automático, las variables categóricas estas deben ser codificadas como variables numéricas, no como cadenas.

Para esta tarea también hay diferentes estrategias, dos comunes son: asociar cadena a número y asociar cadena a columna.

In [ ]:
from sklearn import preprocessing

#### Ejercicio 4

Codificar `currency` con ambas estrategias

In [ ]:
column='currency'
# Create a label (category) encoder object
le = preprocessing.LabelEncoder()
# Fit the encoder to the pandas column
le.fit(kickstarter_2018[column])
kickstarter_2018['coded_currency'] = le.transform(kickstarter_2018[column]) 
kickstarter_2018.head()

In [ ]:
from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()

lb_results = lb.fit_transform(kickstarter_2018[column])
pd.DataFrame(lb_results, columns=((column + '_') + pd.Series(lb.classes_))).head(10)

## 2.4. No cambiar los nombres de las variables de la fuente de origen

## 2.5. Verificar la consistencia de las variables
Aplicar reglas de integridad

#### Ejercicio 5

1. ¿Hay proyecto éxitosos que no consiguieron el objetivo? Si hay, ¿Qué porcentaje sí y cuál no?
2. Calcular una tabla con la cantidad de proyectos por categoría principal y estado.

In [ ]:
kickstarter_2018.columns = kickstarter_2018.columns.str.replace(' ', '_')

exitosos = kickstarter_2018[kickstarter_2018['state'] == 'successful']
cant_exitosos = exitosos.shape[0]
no_objetivo = kickstarter_2018[kickstarter_2018['usd_pledged'] < kickstarter_2018['usd_goal_real']]
cant_no_objetivo = no_objetivo.shape[0]
(cant_no_objetivo * 100) / cant_exitosos
"Porcentaje de proyectos exitosos que no alcanzaron el objetivo: {:.1%}".format(cant_exitosos / cant_no_objetivo)
"Porcentaje de proyectos exitosos que alcanzaron el objetivo: {:.1%}".format(1- (cant_exitosos / cant_no_objetivo))

In [ ]:
"Porcentaje de proyectos exitosos que alcanzaron el objetivo: {:.1%}".format(1- (cant_exitosos / cant_no_objetivo))

In [ ]:
kickstarter_2018.pivot_table(aggfunc=len,index='state',columns='main_category')

## 2.6. Identificar y documentar valores atípicos/outliers

#### Ejercicio 6

Calcular los valores atípicos de 'usd_goal_real' y graficar los boxplots, con y sin estos valores por categoría

In [ ]:
import seaborn
import matplotlib.pyplot as plt
plt.figure(figsize=(15,6))
seaborn.boxplot(data=kickstarter_2018, x='main_category', y='usd_goal_real');

In [ ]:
filter = kickstarter_2018['usd_goal_real'] < 50000
filtered = kickstarter_2018[filter]
plt.figure(figsize=(15,6))
seaborn.boxplot(data=filtered, x='main_category', y='usd_goal_real');